# Generated by Django 3.1.2 on 2021-02-13 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201105_2252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Raiting',
            new_name='Rating',
        ),
        migrations.RenameModel(
            old_name='RaitingStar',
            new_name='RatingStar',
        ),
    ]
